Don't return NULL from function "call"
Returning NULL from function "call" caused an error, as the return is typed ARRAY:
Fatal error:  Uncaught TypeError: Return value of OvhApi::call() must be of the type array, null returned in ...OvhApi.php:121
So the return value in case curl_exec result is false is now an empty array ( [] ).
This case can be detected by if (empty($myout))...